version: '3'
services: 
  db: # container do banco de dados
    image: mongo:3.4
  backend: # container do backend
    image: node:8.1
    volumes:
      - ./backend:/backend:Z # volume mapeado para leitura dos arquivos do backend
    ports:
      - 3000:3000 # expor porta 3000
    command: bash -c "cd /backend && npm i && node app" # entrar na pasta backend,instalar as depêndencias e executar arquivo app.js a partir do node
  frontend: # container do frontend
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/:Z # mapear caminho para leitura dos arquivos frontend
    ports:
      - 80:80 # padrão de porta exposta pelo nginx